from tkinter import*
import random

ara = Tk()

foto = PhotoImage(file = "C:/Users/KOCTEKNO/Downloads/flower-undertale-flower.gif")
photo = Label(ara,image = foto)
photo.pack()
input("naber :" )
print("ben flowey ÇİÇEK flowey!")
input("yolculuğunda yardımcı olucam  ıııı nasıl hissediyorsun?: "  )
input("bugün gerçekten güzel bir gün kuşlar cıvıldıyor çicekler açıyor sence hava nasıl : " )
input("Eeee ben virüs değilim sadeceee  hiç bir program beni sevmediği için siyaha büründüm sence nasıl görünüyorum : " )
şarkı =   input("anladın DOSTUM en sevdiin müzik ne? benimkisi asgore seninkisi ne? : " )
print(şarkı + " hee güzel şarkıymış")
input("hee senle DOST olabileceğimize inanıyorum içim AZİMLE doluyor sen ne durumdasın DOSTUM? : " )
üzücü =  input("demek öyle, ben bir yapay zeka gibi bişey değilim yani beni kapatıp açtığında hep aynı şeyleri söyleyip durucam hiç birşey hatırlamadan üzücü değilmi? : " )
input("kArAnLıKtAn KORKARMISIN DOSTUM : " )
print("etraf karanlık ya ondan sormuştum ")
input(" canının sıkıldığını hissedebiliyorum ama benim İÇİM AZİMLE DOLUYOR beni bırakıcak mısın? : " )
yardım =  input("beni kurtar DOSTUM sana güveniyorum patron w.d. gaster bizi işçi olarak kullanıyorr lütfen dostum LÜTFEN yardım edicekmisin? : " )
print(yardım + " hee")
nasıl =  input("w.d. gaster ı  sadece zekanla yenebilirsin nasıl yenicez? : " )
print(nasıl + " mı aslında iyi fikir" )
input("artık DOST olduğumuza göre bir sırrı senle paylaşabilirim ben flowey ÇİCEK floweyim demiştim ya ben b-ben bir canavardım : " )
print("ahhh sanırım her şeyi anlatmam lazım w.d.gaster diye biride yok seni test ettim")
print("asıl hikaye şu : bir zamanlar 2 ırk vardı insanlar ve CANAVARLAR")
print("bir gün bir savaş çıktı ve insanlar galip geldi.CANAVARları ise sonsuza kadar bir dağa hapsettiler")
print("EBOT DAĞIna ama bir gün canavarlar dağdan kurtuldular ve insanlara yakalanmadılar")
print("yoksa yok olucaklardı yakalanmadılar ve kendilerine bir üst kurdular")
print("o mekanda yaşarkan kralımız yüce ASGORD insanlığa tekrardan savaş açtı")
print("ve yine kaybettik, bizde sonsuza kadar EBOT DAĞInda yaşamaya karar verdik")
print("bende bir çicek canavarı olduğumdan bir sıvı gibi yayılabiliyodum")
print("canavar diyincede aklına kötü şeyler gelmesin biz aslında çok iyi varlıklarız")
print("ve sonsuza kadar EBOT DAĞInda yaşıyoruz bende seninle bir program la konuşuyorum")
input("korkmadın demi DOSTUM : " )
tori =  input("torial adında bir canavar var ve o aynı bir anne gibidir çok güçlüdür ama torial gücünü korumak için kullanır onunla tanışmak istermisin DOSTUM : " )
print(tori + " hee  ben yinede seni tanıştırıcam sana anne gibi bakıcaktır" )
input("torial : selam insan nasılsın ben TORİAL : " )
input("torial : tanıştığıma memnun oldum insan, flowey sana her şeyi anlatmıştır demi : " )
input(" flowey : torial la da DOST oldunmu knk : " )                                                                                                                               
print(" flowey : demek öyle he")
input(" torial : karemallı turta severmisin? : " )
print(" torial : turta yapıyorumda")
input(" torial : insan sana çocuğum diye bilirmiyim ? : " )
print(" torial : tamam çocuğum " )
input(" flowey : DOSTUM torial tanıdığım en iyi canavar değilmi?benden bile iyi : " )
input(" flowey : bu arada her şey çok hızlı oldu özür dilerim çok heyecanlıydım yani ilk defa bi insanla yüz yüze konuşuyorum Eee sorun değil demi : " )
x = random.randint(1,90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
print(" flowey :" +  str(x ))
print("flowey : az önce dediğim şifre, aklında tutarsan belki yararı dokunur")
input(" torial : insan için turtaaa yaptımmm ama doğru insan burda değil neyse, ama turta seversin demi insan? : " )
print(" torial : Eee flowey saklan eşim Asgord gelyoo")
print(" yüce asgord : torial oğlumuz asrial nerde ona ihteyacım varrr " )
input(" torial : sanırım gitti İNSANN asgord sana bişey yaptımı? : " )
print(" torial : endişelenmiştim")
print("flowey : tori sanırım anlatmalıyım")
print("flowey :bu arada torial dreemurr,asgord dreemurr,asrial dreemurr ve frisk dreemurr bir aile ,kraliyet ailesi")
input("torial : oğlum istersen kapat bu kadar derine inmen psikolojini etkiliyebilir çünkü sen canavar değilsin ,oğlum iyimisin? : " )
print(" torial : gerçekten, istersen bu programı kapat kapatıcaksan seni özlicez")
input(" kapatmicaksan 1 yaz : " )
isim =  input("torial : nee kapatmadın bizi bırakmayan tek insan sen gerçekten kraliyet ailesine yakışır bir insansın ismin ne olsun : " )

print("torial : senin ismin " + isim + " dreemurr")
print("flowey : vay be " + isim + " dreemurr havalıymış")
input("torial : " + isim + " dreemurr sen insansın biz ise canavarlarız maalesef aileye katılmak için testlerden geçmelisin, ilk test : DOSTlarına güvenirmisin : " )
print("torial : güzell")
print("flowey : torial ve " + isim + " dreemurr, geç olmadımı? ben yatıcam")
print("torial : " + isim + " dreemurr saat gerçekten geç oldu iyi geceler")
input("sanah olması için 1 yaz : " )
print("torial : " + isim + " dreemurr ve flowey günaydın")
input("flowey : " + isim + " dreemurr EBOT DAĞINda ilk gününü geçirdinn  ne hissediyorsun : " )
print("torial : FLOWEY " + isim + " dreemurr a saçma sapan sorular sorma!! onun adına ben özür dilerim " + isim + " dreemurr")
input("flowey : ne yani " + isim + " dreemurr rahatsız oldumu? : " )
print("torial : bi dakika! " + isim + " dreemurr un aileye katıldığından benden başka kimsenin haberi yok! " + isim + " dreemurr ve flowey ben haber vermeye gidiyorum")
input("flowey : Eee bu sürede " + isim + " dreemurra kim bakıcak asgore mu muhteşem FLOWEY mi : ")
print("flowey : ne dediğinin önemi yok tabikide BENN bakıcamm")
input("torial : F L O W E YYY " + isim + " dreemurra böyle davranmaa.Onun yerine ben özür dilerim çocuğum : ")
print("flowey : t-a-m-a-m  ÖZÜR")
input("torial : ben gidiyorum " + isim + " dreemur çocuğum bana son bişey diyecekmisin : " )
print("torial : tamam çocuğum güle güle hemen gelicem")
input("flowey : ahh knk napalım : ")
print("flowey : tamam knk ben uyicam")
input("yapımcı : " + isim + " DREEMURR İÇİN Bİ SEBEPTEN DOLAYI AZİMLE DOLUYOR ")
print("yapımcı : Eee benim burda olmamam lazım GOOD BYE PLAYER")
input("torial : geldim "+ isim +" dreemurr bebeğim beni özledinmi : ")
print("ailedeki herkes seni çok sevdi tabi ismin " + isim + " dreemurr olunca çok havalı oluyorsun açıkcası")
input("torial : bence en sevdiğin müzik " + şarkı + " doğru bildimmi bebeğim : ")
print(" torial : bu arada en sevdiğim müzik his theme ")
input("torial : bebeğim iyiki benim çocuğumsun " + isim + " dreemurr dünyadaki en iyi evlatsın kendinle gurur duyuyormusun : " )
print(" uzaktaki sesler : KRAL ASGOR " + isim + " DREEMURU İSTİYORR")
input("torial : korkma bebeğim  sadece senle konuşmakc istiyolar bay bay bebeğim beni özlemiceksin değilmi : ")
print("torial : baybay bebeğim kral asgord seni çarıyo")
input("kral sarayına girmek için 1 yaz : ")
print("YÜCE ASGORD : selam " + isim + " dreemurr sana anlatıcağım çok şey var")
print("YÜCE ASGORD : flowey bozuntusu sana tüm hikayeyi yalan dolan anlatmış sana tüm hikayeyi anlatıcam")
print("YÜCE ASGORD : hikaye : 1000 yıl önce 3 ırk vardı insanlar,canavarlar ve yalancılar")
print("YÜCE ASGORD : insanların 4 ruhu vardı bunlar : korkaklık,cesaretlik,savaşcılık ve AZİM ruhuydu,canavarlarda özel büyü ruhu vardı, yalancılara ise ruh yoktu")
print("YÜCE ASGORD :o yüzden yalancılar hep yalan söylerler mesela flowey,korkaklık ruhu hep korkar,cesaret ruhu cesaretlidir,savaşcılık ruhu savaşcıdır, AZİM ruhu iseee")
print("YÜCE ASGORD : azim ruhu hepsinin birleşimidir sende AZİM RUHU  var, büyü ruhu çok güclüdür büyü yapabilir canavarlara o yüzden canavar derler")
print("YÜCE ASGORD : neyse işte 1000 yıl önce bu 3 ırk savaştı ve insanlar  galip geldi ceza olarak yalancılarda canavarlarda aynı yerde yaşamaya başladı")
print("YÜCE ASGORD : o yüzden flowey ve daha fazla yalancı canavarların arasına karıştı")
input("YÜCE ASGORD : senin yeni adında YÜCE " + isim + " DREEMUR olucak,bay bay İNSAN")
input("saraydan çıkmak için 1 yaz : ")
print("torial : bebeğim seninle gurur duyuyorum senin yeni adın YÜCE " + isim + " DREEMURR olmuş")
yalancı =  input("ve artık flowey evimizde değil muhafızlar onu hapse götürdü sebebi ne biliyormusun? : " )
print("torial : " + yalancı + " mı? teşekkürler")
input("torial : sanırım bu hikaye çok uzadı bence programı kapatmalısın hee ne dersin hadi iyiliğin için kapat :" )
input("??? : KAPAT ARTIK LAF ANLAMIYOSAN SEN BİLİRSİN : ")
input("G*S*E* : ne? ismim yavaş yavaş görünüyooo :  " )
input("GAS*ER : HAYIRRRRR HAYIRRRRR DURRRRR : " )
input("GASTER : NO-NOO-N-NOOOOOOOOOOOO olamaz!!! : " )
input("??_????? : bir daha yaparsan : " )
print("SİSTEM ÇÖKÜYOR,İÇİN AZİMLE DOLUYOR!!! (BAŞARDIN " + isim + " DREEMURR,BAŞARDIN!")
print("NPCLER : YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK,YÜCE ASGORD BİZİ ÖZGÜR YAŞATICAK")


input("""  UNDERTALE BY TOBY FOX
                UNDFELL BY ALPARSLAN ALİ
                THANK FOR PLAYİNG""")

ara.mainloop()





